-- Claude account login + the OAuth-specific Messages request shape. Offline.
package.path = 'scripts/?.lua;' .. package.path
local spec=dofile('tests/lua/spec_helper.lua')
local json=require('xutils')
local auth=require('xagent.auth.claude')
local chatgpt=require('xagent.auth.chatgpt')
local anthropic=require('xagent.llm.anthropic')
local httpcodec=dofile('scripts/core/share/xhttp_codec.lua')
local saved, writes
local function reset(value)
    auth.cancel(); saved=value; writes=0
    auth.set_storage({load=function() return saved end,save=function(v) saved=v;writes=writes+1;return true end})
end
local function token(body) return nil,{status=200,body=json.json_pack(body)} end
spec.describe('Claude authentication',function()
    spec.it('uses the Claude manual callback and JSON token exchange',function()
        reset()
        local url=auth.begin('socks5://localhost:1080')
        spec.contains(url,'https://claude.ai/oauth/authorize?')
        local q=httpcodec.parse_query(url:match('%?(.*)'))
        spec.equal(q.code_challenge_method,'S256');spec.equal(q.code,'true')
        spec.equal(q.scope,'org:create_api_key user:profile user:inference')
        spec.equal(q.redirect_uri,'https://console.anthropic.com/oauth/code/callback')
        local v=auth.finish('test-code#' .. q.state,function(opts)
            spec.equal(opts.headers['Content-Type'],'application/json')
            local body=json.json_unpack(opts.body)
            spec.equal(body.grant_type,'authorization_code');spec.equal(body.state,q.state)
            spec.equal(body.client_id,'9d1c250a-e61b-44d9-88ed-5944d1962f5e')
            spec.equal(#body.code_verifier,64);spec.equal(opts.proxy,'socks5://localhost:1080')
            return token({access_token='test-access',refresh_token='test-refresh',expires_in=100,
                account={uuid='acct',email_address='test@example.invalid'}})
        end)
        spec.equal(v.access_token,'test-access');spec.equal(v.account_id,'acct')
        spec.equal(v.email,'test@example.invalid');spec.equal(writes,1)
        spec.equal(pcall(auth.finish,{state=q.state,code='replay'}),false)
    end)
    spec.it('keeps its login state separate from ChatGPT',function()
        reset();chatgpt.cancel()
        local url=auth.begin();local q=httpcodec.parse_query(url:match('%?(.*)'))
        spec.equal(pcall(chatgpt.finish,{state=q.state,code='x'}),false)
        auth.finish({state=q.state,code='x'},function() return token({access_token='a',refresh_token='r'}) end)
        spec.equal(writes,1)
    end)
    spec.it('refreshes with a JSON body and keeps the refresh token',function()
        reset({access_token='old',refresh_token='refresh',expires_at=0,email='e'})
        local v=auth.ensure(nil,function(opts)
            local body=json.json_unpack(opts.body)
            spec.equal(body.grant_type,'refresh_token');spec.equal(body.refresh_token,'refresh')
            return token({access_token='new',expires_in=3600})
        end,100)
        spec.equal(v.access_token,'new');spec.equal(v.refresh_token,'refresh')
        spec.equal(v.email,'e');spec.equal(v.expires_at,3700)
    end)
end)
spec.describe('Claude OAuth Messages request',function()
    spec.it('sends Bearer + OAuth beta and leads the system prompt with the identity block',function()
        local req=anthropic.build_request({api_key='tok',auth_type='claude',auth_style='bearer'},
            {messages={{role='user',content='hi'}},system='SYS'})
        spec.equal(req.headers['authorization'],'Bearer tok');spec.nil_value(req.headers['x-api-key'])
        spec.equal(req.headers['anthropic-beta'],'oauth-2025-04-20,interleaved-thinking-2025-05-14,claude-code-20250219,fine-grained-tool-streaming-2025-05-14')
        local body=json.json_unpack(req.body)
        spec.contains(body.system[1].text,'Claude Code');spec.equal(body.system[2].text,'SYS')
        spec.truthy(body.system[2].cache_control)
    end)
    spec.it('leaves API-key requests unchanged',function()
        local req=anthropic.build_request({api_key='k'},{messages={{role='user',content='hi'}},system='SYS'})
        spec.nil_value(req.headers['anthropic-beta']);spec.equal(req.headers['x-api-key'],'k')
        spec.equal(#json.json_unpack(req.body).system,1)
    end)
    spec.it('replaces built-in identity only for Claude without mutating the prompt',function()
        local text=require('xagent.context.system_prompt').build({cwd='.'})
        local blocks={{type='text',text=text}}
        local req=anthropic.build_request({api_key='tok',auth_type='claude',auth_style='bearer'},
            {messages={},system=blocks})
        local body=json.json_unpack(req.body)
        spec.equal(body.system[2].text:find('You are xagent',1,true),nil)
        spec.equal(blocks[1].text,text)
        local normal=anthropic.build_request({api_key='key'},{messages={},system=text})
        spec.contains(normal.body,'You are xagent')
    end)
end)
local failures=spec.finish()
return {__init=function() if failures>0 then os.exit(1) end;xthread.stop(0) end}
